### ISSUE TITLE
Melhorar tradução de: "We are punished by our sins, not for them."

### ISSUE THREAD

**Issue by brunolemos** [brunolemos/trust#4]
Frase: `We are punished by our sins, not for them.`
Qual seria a melhor tradução? Uma que não seja necessariamente ao pé da letra, mas que tenha o mesmo sentido filosófico que o autor quis passar.

Atual tradução: `Somos castigados pelos pecados que cometemos.`
Não me parece muito certo.

Alguma sugestão?

**Comment by mpaugus** [comment]
Que tal: "Somos castigados pelos nossos pecados, e não por causa deles."

**Comment by brunolemos** [comment]
@mpaugus Pode ser, você quer adicionar essa edição no arquivo? https://github.com/brunolemos/trust/blob/gh-pages/words.html#L530

**Comment by brunolemos** [comment]
#8
