### ISSUE TITLE
Correção tradução 

### ISSUE THREAD

**Issue by wisnerjr** [brunolemos/trust#5]
Na Seção "8. Conclusão", a palavra "frequente" está com acento circunflexo tanto no título do primeiro item quanto em sua descrição. Apenas um detalhe :D

![correcao_traducao](https://user-images.githubusercontent.com/13546789/32015688-968dd7fc-b9a0-11e7-974d-d781a7ab790a.jpg)

**Comment by brunolemos** [comment]
@wisnerjr você pode editar o arquivo no github se preferir, daí eu aceito o pull request

**Comment by wisnerjr** [comment]
beleza, assim que eu chegar em casa eu faço isso :+1:

**Comment by wisnerjr** [comment]
Vou fechar essa issue já que eu fiz o PR da correção hahaha
